[package]
name = "web_ui"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
tower = "0.5"
tower-http = { version = "0.6", features = ["fs"] }
tokio = { version = "1.46", features = ["full"] }